In [18]:
import os
import xml.etree.ElementTree as et
import pandas as pd

In [4]:
results_page = pd.read_csv("results.csv")

In [5]:
results_page.head()

,line number,contest name,choice name,party name,total votes,percent of votes,registered voters,ballots cast,num Precinct total,num Precinct rptg,over votes,under votes
0,1,US Senate - Rep (Vote For 1),Gary W. Black,REP,157370,13.35,0,0,159,159,0,100
1,2,US Senate - Rep (Vote For 1),Josh Clark,REP,46693,3.96,0,0,159,159,0,100
2,3,US Senate - Rep (Vote For 1),Kelvin King,REP,37930,3.22,0,0,159,159,0,100
3,4,US Senate - Rep (Vote For 1),"Jonathan """"Jon"""" McColumn",REP,28601,2.43,0,0,159,159,0,100
4,5,US Senate - Rep (Vote For 1),Latham Saddler,REP,104471,8.86,0,0,159,159,0,100

In [9]:
results_bycounty_page = pd.read_csv("results_by_county.csv")

In [10]:
results_bycounty_page.head()

,line number,contest name,choice name,party name,total votes,percent of votes,registered voters,ballots cast,num Precinct total,num Precinct rptg,over votes,under votes
0,1,US Senate - Rep (Vote For 1),Gary W. Black,REP,157370,13.35,0,0,159,159,0,100
1,2,US Senate - Rep (Vote For 1),Josh Clark,REP,46693,3.96,0,0,159,159,0,100
2,3,US Senate - Rep (Vote For 1),Kelvin King,REP,37930,3.22,0,0,159,159,0,100
3,4,US Senate - Rep (Vote For 1),"Jonathan """"Jon"""" McColumn",REP,28601,2.43,0,0,159,159,0,100
4,5,US Senate - Rep (Vote For 1),Latham Saddler,REP,104471,8.86,0,0,159,159,0,100

In [11]:
results_page == results_bycounty_page

,line number,contest name,choice name,party name,total votes,percent of votes,registered voters,ballots cast,num Precinct total,num Precinct rptg,over votes,under votes
0,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
798,True,True,True,True,True,True,True,True,True,True,True,True
799,True,True,True,True,True,True,True,True,True,True,True,True
800,True,True,True,True,True,True,True,True,True,True,True,True
801,True,True,True,True,True,True,True,True,True,True,True,True
802,True,True,True,True,True,True,True,True,True,True,True,True

In [14]:
primary_sos_totals = pd.read_csv("./raw-from-source/summary/summary.csv")
combined_sos_totals = pd.concat([primary_sos_totals])

In [16]:
primary_sos_totals == results_page

,line number,contest name,choice name,party name,total votes,percent of votes,registered voters,ballots cast,num Precinct total,num Precinct rptg,over votes,under votes
0,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
798,True,True,True,True,True,True,True,True,True,True,True,True
799,True,True,True,True,True,True,True,True,True,True,True,True
800,True,True,True,True,True,True,True,True,True,True,True,True
801,True,True,True,True,True,True,True,True,True,True,True,True
802,True,True,True,True,True,True,True,True,True,True,True,True

In [13]:
primary_sos_totals.head()

,line number,contest name,choice name,party name,total votes,percent of votes,registered voters,ballots cast,num Precinct total,num Precinct rptg,over votes,under votes
0,1,US Senate - Rep (Vote For 1),Gary W. Black,REP,157370,13.35,0,0,159,159,0,100
1,2,US Senate - Rep (Vote For 1),Josh Clark,REP,46693,3.96,0,0,159,159,0,100
2,3,US Senate - Rep (Vote For 1),Kelvin King,REP,37930,3.22,0,0,159,159,0,100
3,4,US Senate - Rep (Vote For 1),"Jonathan """"Jon"""" McColumn",REP,28601,2.43,0,0,159,159,0,100
4,5,US Senate - Rep (Vote For 1),Latham Saddler,REP,104471,8.86,0,0,159,159,0,100

In [19]:
loaded_counties = os.listdir("./raw-from-source/summary/county_checks")
z=[]
for locale in loaded_counties:
    if locale.endswith('.xml'):
        file_string = "./raw-from-source/summary/county_checks/"+locale
        xtree = et.parse(file_string)
        xroot = xtree.getroot()
        state_area = xroot.findall(".//Region")
        for i in state_area:
            state = i.text
        contests = xroot.findall(".//Contest")
        for i in contests:
            contest = i.attrib.get('text')
            lower = i.findall("./Choice")
            for j in lower:
                choice = j.attrib.get('text')
                lower_2 = j.findall("./VoteType")
                for k in lower_2:
                    voting_method = k.attrib.get('name')
                    lower_3 = k.findall("./County")
                    for l in lower_3:
                        county_name = l.attrib.get('name')
                        num_votes = l.attrib.get('votes')
                        if locale == "detail 2.xml":
                            elec_type = "special"
                        else:
                            elec_type = "primary"
                        z.append([state,contest,choice,voting_method,county_name,num_votes, elec_type])
dfcols = ['state','contest','choice','voting_method','county','num_votes',"type"]
county_xml = pd.DataFrame(z,columns=dfcols)

In [27]:
county_xml['num_votes'] = county_xml['num_votes'].astype(int)

In [28]:
county_xml.loc[county_xml['choice'] == 'Gary W. Black']['num_votes'].sum()

157370

In [23]:
county_xml.head()

,state,contest,choice,voting_method,county,num_votes,type
0,GA,US Senate - Rep,Gary W. Black,Election Day Votes,Appling,401,primary
1,GA,US Senate - Rep,Gary W. Black,Election Day Votes,Atkinson,102,primary
2,GA,US Senate - Rep,Gary W. Black,Election Day Votes,Bacon,158,primary
3,GA,US Senate - Rep,Gary W. Black,Election Day Votes,Baker,104,primary
4,GA,US Senate - Rep,Gary W. Black,Election Day Votes,Baldwin,279,primary